<a href="https://colab.research.google.com/github/donw385/DS-Unit-2-Sprint-3-Advanced-Regression/blob/master/Don_Wang_DS_Unit_2_Sprint_Challenge_3_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science Unit 2 Sprint Challenge 3

## Logistic Regression and Beyond

In this sprint challenge you will fit a logistic regression modeling the probability of an adult having an income above 50K. The dataset is available at UCI:

https://archive.ics.uci.edu/ml/datasets/adult

Your goal is to:

1. Load, validate, and clean/prepare the data.
2. Fit a logistic regression model
3. Answer questions based on the results (as well as a few extra questions about the other modules)

Don't let the perfect be the enemy of the good! Manage your time, and make sure to get to all parts. If you get stuck wrestling with the data, simplify it (if necessary, drop features or rows) so you're able to move on. If you have time at the end, you can go back and try to fix/improve.

### Hints

It has a variety of features - some are continuous, but many are categorical. You may find [pandas.get_dummies](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html) (a method to one-hot encode) helpful!

The features have dramatically different ranges. You may find [sklearn.preprocessing.minmax_scale](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.minmax_scale.html#sklearn.preprocessing.minmax_scale) helpful!

## Part 1 - Load, validate, and prepare data

The data is available at: https://archive.ics.uci.edu/ml/datasets/adult

Load it, name the columns, and make sure that you've loaded the data successfully. Note that missing values for categorical variables can essentially be considered another category ("unknown"), and may not need to be dropped.

You should also prepare the data for logistic regression - one-hot encode categorical features as appropriate.

In [0]:
# all imports at beginning

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.preprocessing import scale
from sklearn.preprocessing import minmax_scale



pd.set_option('display.max_columns', 500)

In [2]:
#only using data file


df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',header=None)
df.columns = ['age','workclass','fnlwgt','education','education_num','marital','occupation','relationship','race','sex','capitalgain','capitalloss','hours_week','home_country','income']


df.head(500)

,age,workclass,fnlwgt,education,education_num,marital,occupation,relationship,race,sex,capitalgain,capitalloss,hours_week,home_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,60,Private,201965,Some-college,10,Never-married,Prof-specialty,Unmarried,White,Male,0,0,40,United-States,>50K
471,22,?,139883,Some-college,10,Never-married,?,Own-child,White,Male,0,0,40,United-States,<=50K
472,35,Private,285020,HS-grad,9,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,United-States,<=50K
473,30,Private,303990,HS-grad,9,Never-married,Transport-moving,Not-in-family,White,Male,0,0,60,United-States,<=50K
474,67,Private,49401,Assoc-voc,11,Divorced,Other-service,Not-in-family,White,Female,0,0,24,United-States,<=50K
475,46,Private,279196,Bachelors,13,Never-married,Craft-repair,Not-in-family,White,Female,0,0,40,United-States,<=50K
476,17,Private,211870,9th,5,Never-married,Other-service,Not-in-family,White,Male,0,0,6,United-States,<=50K
477,22,Private,281432,Some-college,10,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,30,United-States,<=50K
478,27,Private,161155,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,40,United-States,<=50K
479,23,Private,197904,HS-grad,9,Never-married,Other-service,Unmarried,White,Female,0,0,35,United-States,<=50K
480,33,Private,111746,Assoc-acdm,12,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,45,Portugal,<=50K
481,43,Self-emp-not-inc,170721,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,20,United-States,<=50K
482,28,State-gov,70100,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,20,United-States,<=50K
483,41,Private,193626,HS-grad,9,Married-spouse-absent,Craft-repair,Unmarried,White,Female,0,0,40,United-States,<=50K
484,52,?,271749,12th,8,Never-married,?,Other-relative,Black,Male,594,0,40,United-States,<=50K
485,25,Private,189775,Some-college,10,Married-spouse-absent,Adm-clerical,Own-child,Black,Female,0,0,20,United-States,<=50K
486,63,?,401531,1st-4th,2,Married-civ-spouse,?,Husband,White,Male,0,0,35,United-States,<=50K
487,59,Local-gov,286967,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,45,United-States,<=50K
488,45,Local-gov,164427,Bachelors,13,Divorced,Prof-specialty,Unmarried,White,Female,0,0,40,United-States,<=50K
489,38,Private,91039,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,15024,0,60,United-States,>50K
490,40,Private,347934,HS-grad,9,Never-married,Other-service,Not-in-family,White,Female,0,0,35,United-States,<=50K
491,46,Federal-gov,371373,HS-grad,9,Divorced,Adm-clerical,Not-in-family,White,Male,0,0,40,United-States,<=50K
492,35,Private,32220,Assoc-acdm,12,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,60,United-States,<=50K
493,34,Private,187251,HS-grad,9,Divorced,Prof-specialty,Unmarried,White,Female,0,0,25,United-States,<=50K
494,33,Private,178107,Bachelors,13,Never-married,Craft-repair,Own-child,White,Male,0,0,20,United-States,<=50K
495,41,Private,343121,HS-grad,9,Divorced,Adm-clerical,Unmarried,White,Female,0,0,36,United-States,<=50K
496,20,Private,262749,Some-college,10,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,<=50K
497,23,Private,403107,5th-6th,3,Never-married,Other-service,Own-child,White,Male,0,0,40,El-Salvador,<=50K
498,26,Private,64293,Some-college,10,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,35,United-States,<=50K
499,72,?,303588,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,20,United-States,<=50K

In [0]:
df = pd.get_dummies(df).drop('income_ <=50K', axis = 'columns')

In [11]:
df.describe()

,age,fnlwgt,education_num,capitalgain,capitalloss,hours_week,workclass_ ?,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,workclass_ Private,workclass_ Self-emp-inc,workclass_ Self-emp-not-inc,workclass_ State-gov,workclass_ Without-pay,education_ 10th,education_ 11th,education_ 12th,education_ 1st-4th,education_ 5th-6th,education_ 7th-8th,education_ 9th,education_ Assoc-acdm,education_ Assoc-voc,education_ Bachelors,education_ Doctorate,education_ HS-grad,education_ Masters,education_ Preschool,education_ Prof-school,education_ Some-college,marital_ Divorced,marital_ Married-AF-spouse,marital_ Married-civ-spouse,marital_ Married-spouse-absent,marital_ Never-married,marital_ Separated,marital_ Widowed,occupation_ ?,occupation_ Adm-clerical,occupation_ Armed-Forces,occupation_ Craft-repair,occupation_ Exec-managerial,occupation_ Farming-fishing,occupation_ Handlers-cleaners,occupation_ Machine-op-inspct,occupation_ Other-service,occupation_ Priv-house-serv,occupation_ Prof-specialty,occupation_ Protective-serv,occupation_ Sales,occupation_ Tech-support,occupation_ Transport-moving,relationship_ Husband,relationship_ Not-in-family,relationship_ Other-relative,relationship_ Own-child,relationship_ Unmarried,relationship_ Wife,race_ Amer-Indian-Eskimo,race_ Asian-Pac-Islander,race_ Black,race_ Other,race_ White,sex_ Female,sex_ Male,home_country_ ?,home_country_ Cambodia,home_country_ Canada,home_country_ China,home_country_ Columbia,home_country_ Cuba,home_country_ Dominican-Republic,home_country_ Ecuador,home_country_ El-Salvador,home_country_ England,home_country_ France,home_country_ Germany,home_country_ Greece,home_country_ Guatemala,home_country_ Haiti,home_country_ Holand-Netherlands,home_country_ Honduras,home_country_ Hong,home_country_ Hungary,home_country_ India,home_country_ Iran,home_country_ Ireland,home_country_ Italy,home_country_ Jamaica,home_country_ Japan,home_country_ Laos,home_country_ Mexico,home_country_ Nicaragua,home_country_ Outlying-US(Guam-USVI-etc),home_country_ Peru,home_country_ Philippines,home_country_ Poland,home_country_ Portugal,home_country_ Puerto-Rico,home_country_ Scotland,home_country_ South,home_country_ Taiwan,home_country_ Thailand,home_country_ Trinadad&Tobago,home_country_ United-States,home_country_ Vietnam,home_country_ Yugoslavia,income_ >50K
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.0000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456,0.056386,0.029483,0.064279,0.000215,0.697030,0.034274,0.078038,0.039864,0.000430,0.028654,0.036086,0.013298,0.005160,0.010227,0.019840,0.015786,0.032769,0.042443,0.164461,0.012684,0.322502,0.052916,0.001566,0.017690,0.223918,0.136452,0.000706,0.459937,0.012837,0.328092,0.031479,0.030497,0.056601,0.115783,0.000276,0.125887,0.124873,0.030527,0.042075,0.061485,0.101195,0.004576,0.127146,0.019932,0.112097,0.0285,0.049046,0.405178,0.255060,0.030128,0.155646,0.105832,0.048156,0.009551,0.031909,0.095943,0.008323,0.854274,0.330795,0.669205,0.017905,0.000584,0.003716,0.002303,0.001812,0.002918,0.002150,0.000860,0.003255,0.002764,0.000891,0.004207,0.000891,0.001966,0.001351,0.000031,0.000399,0.000614,0.000399,0.003071,0.001321,0.000737,0.002242,0.002488,0.001904,0.000553,0.019748,0.001044,0.000430,0.000952,0.006081,0.001843,0.001136,0.003501,0.000369,0.002457,0.001566,0.000553,0.000584,0.895857,0.002058,0.000491,0.240810
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429,0.230670,0.169159,0.245254,0.014661,0.459549,0.181935,0.268236,0.195642,0.020731,0.166834,0.186507,0.114550,0.071646,0.100612,0.139451,0.124648,0.178035,0.201602,0.370699,0.111908,0.467441,0.223869,0.039546,0.131824,0.416874,0.343273,0.026569,0.498400,0.112575,0.469526,0.174612,0.171952,0.231083,0.319969,0.016623,0.331727,0.330580,0.172036,0.200763,0.240221,0.301591,0.067492,0.333142,0.139768,0.315491,0.1664,0.215968,0.490934,0.435901,0.170942,0.362525,0.307627,0.214099,0.097264,0.175761,0.294518,0.090851,0.352837,0.470506,0.470506,0.132608,0.024149,0.060847,0.047939,0.042529,0.053937,0.046317,0.029312,0.056964,0.052502,0.029831,0.064730,0.029831,0.044292,0.036736,0.005542,0.019978,0.024776,0.019978,0.055334,0.036317,0.027140,0.047297,0.049815,0.043595,0.023506,0.139134,0.032298,0.020731,0.030841,0.077744,0.042888,0.033691,0.059068,0.019194,0.049507,0.039546,0.023506,0.024149,0.305451,0.045316,0.022162,0.427581
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

## Part 2 - Fit and present a Logistic Regression

Your data should now be in a state to fit a logistic regression. Use scikit-learn, define your `X` (independent variable) and `y`, and fit a model.

Then, present results - display coefficients in as interpretible a way as you can (hint - scaling the numeric features will help, as it will at least make coefficients more comparable to each other). If you find it helpful for interpretation, you can also generate predictions for cases (like our 5 year old rich kid on the Titanic) or make visualizations - but the goal is your exploration to be able to answer the question, not any particular plot (i.e. don't worry about polishing it).

It is *optional* to use `train_test_split` or validate your model more generally - that is not the core focus for this week. So, it is suggested you focus on fitting a model first, and if you have time at the end you can do further validation.

In [13]:
#logistic regression. score of 0.85 means 85% of y is explained by X variables

X = minmax_scale(df.drop('income_ >50K',axis='columns'))
y = df['income_ >50K']

log_reg = LogisticRegression(solver='lbfgs').fit(X, y)
log_reg.score(X, y)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype uint8, int64 were all converted to float64.

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

0.8520008599244495

In [14]:
#everything scaled zero to 1

X[0]

array([0.30136986, 0.0443019 , 0.8       , 0.02174022, 0.        ,
       0.39795918, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ,
       1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        ])

In [15]:
log_reg.coef_

array([[ 1.82078466e+00,  9.56862960e-01,  1.72738793e+00,
         1.80195204e+01,  2.56167022e+00,  2.77324288e+00,
        -3.31850340e-01,  3.31170183e-01, -3.22753561e-01,
        -1.76776048e-01, -1.50234407e-01,  3.47730183e-02,
        -6.21155991e-01, -4.61310621e-01, -1.11363338e+00,
        -6.64250266e-01, -6.65816813e-01, -3.84985342e-01,
        -6.21899140e-01, -5.11685283e-01, -8.71374533e-01,
        -7.55961475e-01, -4.28348367e-02,  9.55159915e-02,
         4.31763321e-01,  1.08210221e+00, -2.16129728e-01,
         6.70617699e-01, -1.38223053e+00,  1.01817353e+00,
         7.22404653e-03, -9.21292860e-01,  1.20904975e+00,
         1.02602249e+00, -8.99947965e-01, -1.38751413e+00,
        -1.04479960e+00, -7.93288836e-01, -5.08626388e-01,
        -2.31901592e-02, -4.11794641e-01,  4.85790147e-02,
         7.49441145e-01, -9.68341612e-01, -6.93907227e-01,
        -3.05686342e-01, -8.55969025e-01, -1.58034621e+00,
         4.93055641e-01,  5.21233525e-01,  2.53166611e-01,
         6.08615525e-01, -1.38001009e-01, -5.68336266e-01,
        -2.03628572e-01, -1.03841047e+00, -1.36990968e+00,
        -3.66170342e-01,  7.34684176e-01, -8.45617033e-01,
        -2.98264529e-01, -5.37666615e-01, -7.49715555e-01,
        -3.80507416e-01, -1.81796396e+00, -9.93807191e-01,
        -8.93802543e-02,  9.57712667e-01,  3.78268135e-01,
        -5.00102040e-01, -1.30833920e+00,  3.93605111e-01,
        -1.04072901e+00, -1.37688850e-01, -3.41099091e-01,
         3.96049559e-01,  5.84500403e-01,  5.01017936e-01,
        -5.75912555e-01, -9.72576000e-02, -3.19161484e-02,
        -1.44626922e-02, -2.16794159e-01, -3.73127575e-02,
         1.72760546e-02, -2.43063014e-01,  9.10362190e-02,
         4.44164301e-01,  8.10444218e-01,  6.05511333e-02,
         4.31788292e-01, -3.21358972e-01, -4.97070960e-01,
        -4.95881194e-01, -7.11940933e-01, -4.81865538e-01,
         4.70916162e-01,  8.53374054e-02,  1.83773222e-02,
        -2.00334962e-01,  8.28404208e-02, -8.36038817e-01,
         7.96233285e-02, -3.06174359e-01, -2.09235775e-01,
         2.89621581e-01, -7.43199471e-01,  5.32256954e-01]])

In [16]:
for name, coef in zip(df.columns, log_reg.coef_[0]):
  print(name, coef)

age 1.8207846550728866
fnlwgt 0.9568629597182766
education_num 1.7273879339737481
capitalgain 18.01952041399977
capitalloss 2.5616702187450366
hours_week 2.7732428799418933
workclass_ ? -0.33185034039203487
workclass_ Federal-gov 0.3311701832411861
workclass_ Local-gov -0.3227535611312708
workclass_ Never-worked -0.17677604799199706
workclass_ Private -0.15023440722624046
workclass_ Self-emp-inc 0.03477301832814006
workclass_ Self-emp-not-inc -0.6211559907548447
workclass_ State-gov -0.4613106206260706
workclass_ Without-pay -1.1136333822132134
education_ 10th -0.664250265848197
education_ 11th -0.6658168134237571
education_ 12th -0.3849853422994742
education_ 1st-4th -0.6218991400708158
education_ 5th-6th -0.5116852832149984
education_ 7th-8th -0.871374533159814
education_ 9th -0.7559614752883024
education_ Assoc-acdm -0.04283483670303685
education_ Assoc-voc 0.0955159914513114
education_ Bachelors 0.4317633206464767
education_ Doctorate 1.0821022095163542
education_ HS-grad -0.2161297276996569
education_ Masters 0.67061769904451
education_ Preschool -1.3822305294220094
education_ Prof-school 1.018173531184577
education_ Some-college 0.00722404653283871
marital_ Divorced -0.9212928598324694
marital_ Married-AF-spouse 1.2090497502524855
marital_ Married-civ-spouse 1.0260224939111529
marital_ Married-spouse-absent -0.8999479652839926
marital_ Never-married -1.387514130105976
marital_ Separated -1.0447996017001129
marital_ Widowed -0.7932888360010399
occupation_ ? -0.5086263883840318
occupation_ Adm-clerical -0.023190159246221493
occupation_ Armed-Forces -0.41179464117898745
occupation_ Craft-repair 0.04857901466089425
occupation_ Exec-managerial 0.7494411454441846
occupation_ Farming-fishing -0.9683416124939888
occupation_ Handlers-cleaners -0.6939072270764138
occupation_ Machine-op-inspct -0.3056863420132263
occupation_ Other-service -0.8559690247790228
occupation_ Priv-house-serv -1.5803462060279874
occupation_ Prof-specialty 0.49305564074746183
occupation_ Protective-serv 0.521233524966562
occupation_ Sales 0.25316661085357717
occupation_ Tech-support 0.6086155252591242
occupation_ Transport-moving -0.1380010094861156
relationship_ Husband -0.5683362656613395
relationship_ Not-in-family -0.20362857232862738
relationship_ Other-relative -1.038410468319014
relationship_ Own-child -1.3699096773356294
relationship_ Unmarried -0.3661703415713921
relationship_ Wife 0.7346841764541888
race_ Amer-Indian-Eskimo -0.8456170331378401
race_ Asian-Pac-Islander -0.298264529238885
race_ Black -0.537666615458306
race_ Other -0.7497155548874123
race_ White -0.38050741602584554
sex_ Female -1.817963958058443
sex_ Male -0.993807190699052
home_country_ ? -0.08938025429239725
home_country_ Cambodia 0.9577126666017923
home_country_ Canada 0.3782681347231809
home_country_ China -0.5001020403878017
home_country_ Columbia -1.3083391957633934
home_country_ Cuba 0.39360511124121483
home_country_ Dominican-Republic -1.040729010490332
home_country_ Ecuador -0.13768885018589014
home_country_ El-Salvador -0.3410990908100909
home_country_ England 0.396049558700307
home_country_ France 0.5845004025202232
home_country_ Germany 0.5010179359333586
home_country_ Greece -0.5759125553409427
home_country_ Guatemala -0.09725760001166293
home_country_ Haiti -0.03191614841910311
home_country_ Holand-Netherlands -0.014462692158344287
home_country_ Honduras -0.21679415930301438
home_country_ Hong -0.03731275747978884
home_country_ Hungary 0.017276054643648304
home_country_ India -0.2430630144319425
home_country_ Iran 0.0910362190374957
home_country_ Ireland 0.4441643011318312
home_country_ Italy 0.8104442176965597
home_country_ Jamaica 0.0605511333205986
home_country_ Japan 0.4317882919111328
home_country_ Laos -0.32135897167729244
home_country_ Mexico -0.4970709599763935
home_country_ Nicaragua -0.49588119390264845
home_country_ Outlying-US(Guam-USVI-etc) -0.7119409333337076
home_country_ Peru -0.4818655379870458
home_country_ Philippines 0.47091616181781437
home_country_ Poland 0.0853374054289461
home_country_ Portugal 0.018377322221974073
home_country_ Puerto-Rico -0.20033496234951126
home_country_ Scotland 0.08284042078958528
home_country_ South -0.8360388174599376
home_country_ Taiwan 0.07962332850480053
home_country_ Thailand -0.3061743593163868
home_country_ Trinadad&Tobago -0.20923577460680615
home_country_ United-States 0.2896215813726194
home_country_ Vietnam -0.7431994707002554
home_country_ Yugoslavia 0.532256954038041

In [17]:
#linear regression for comparison. as you can see, the score of 0.37 is much lower than logistic regression score

linear_reg = LinearRegression().fit(X, y)
linear_reg.score(X, y)

0.3691028325604114

## Part 3 - Analysis, Interpretation, and Questions

### Based on your above model, answer the following questions

1. What are 3 features positively correlated with income above 50k?
2. What are 3 features negatively correlated with income above 50k?
3. Overall, how well does the model explain the data and what insights do you derive from it?

*These answers count* - that is, make sure to spend some time on them, connecting to your analysis above. There is no single right answer, but as long as you support your reasoning with evidence you are on the right track.

Note - scikit-learn logistic regression does *not* automatically perform a hypothesis test on coefficients. That is OK - if you scale the data they are more comparable in weight.

### Match the following situation descriptions with the model most appropriate to addressing them

In addition to logistic regression, a number of other approaches were covered this week. Pair them with the situations they are most appropriate for, and briefly explain why.

Situations:
1. You are given data on academic performance of primary school students, and asked to fit a model to help predict "at-risk" students who are likely to receive the bottom tier of grades.
2. You are studying tech companies and their patterns in releasing new products, and would like to be able to model and predict when a new product is likely to be launched.
3. You are working on modeling expected plant size and yield with a laboratory that is able to capture fantastically detailed physical data about plants, but only of a few dozen plants at a time.

Approaches:
1. Ridge Regression
2. Quantile Regression
3. Survival Analysis

**Model Question 1**

In my scaled, logistic regression, I looked for the 3 highest positive coefficients, which would be the 3 strongest positive correlations with incomes over $50K.

The first was capital gains, with a very high coefficient of 2.321904, which makes sense, because the more capital gains you have, the more chance you have of making more money.

The second is sex, which was 0.887185, which implied that males (which were coded 1) have a much higher chance of earning $50K. This makes sense, because of both the well documentated pay discrepancy between men and women, as well as more women being homemakers than men.	

The third is education number of years, which was 0.855879, which makes sense because the more education you have, the more skills you have, so are more likely to land a high paying job.

**Model Question 2**

In my logistic regression, work class, or type of work (e.g. Private, Self-Employed, Gov., etc.) has a negative coefficient of -0.022047, which means it is negatively correlated with incomes >$50K. This makes sense to me as some of the higher code values are government jobs, which tend to be lower paying than private.

Additionally, marital status  has a negative coefficient of -0.236281, which also implies negative correlation. Never married, separated, and widowed are high code values, which implies if someone is in these categories, they are less likely to have an income greater than $50K. 

Lastly, relationship status has a negative coefficient of -0.120923, which implies negative correlation. I am not sure what the values mean, but this analysis shows that a person with higher code values are less likely to have an income greater than $50K. 

**Model Question 3**

The scaled logistic model fits the data pretty well, with a score of 0.825, meaning that  83% of y is explained by X variables. This is higher than the logistic model without scaling of 0.79, and much higher than the linear regression number of 0.26.

In addition to the analysis listed in Questions 1 and 2, it is interesting to note that the negative coefficients were much lower than the positive ones, which could be due to the numbers being category labels. If I had more time, I would do further work on the category labels and classify them into binary 0 and 1 values, which woud give a much clearer picture, but in the time frame and information given, I did not have a solid enough understanding to do this. Thus, it can be concluded that although the negative correlations do exist, more analysis can be performed to understand the true relationship.


**Other Techniques Question**

Survival analysis would best be used for Option 2, the tech product launch because it is good for analyzing birth events, which is what the product launch is.

Quantile regression is best used for Option 1, the bottom tier student analysis, because you are centering the analysis around a lower quantile, not the middle of the data set, which is best done with quantile regression.

Ridge regression is best used for Option 3, on modeling plant size, because we don't want to overfit the data on such a small sample size, which ridge regression helps to achieve to get a better answer for small subsets of data.